name: fleather
description: Clean, minimalistic and collaboration-ready rich text editor for Flutter.
version: 1.0.0
homepage: https://github.com/fleather-editor/fleather
publish_to: none

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.16.0
  quill_delta: ^3.0.0-nullsafety.2
  parchment:
    git:
      url: https://github.com/Taskulu/fleather
      path: packages/parchment
      ref: taskulu_edition
  characters: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
